### ISSUE TITLE
Irrevocable Attestations?

### ISSUE THREAD

**Issue by ccamrobertson** [ethereum-attestation-service/contracts#14]
Looking forward to the impending launch!

I wanted to see if there was any consideration to creating irrevocable attestations. We're working on some protocol pieces around secure chips and a key part of this is creating certificates whereby parties sign the chips (e.g. the manufacturer). In our case we never want to allow for the revocation of this kind of attestation; if a manufacturer made a chip with given information, that fact should never change.

A similar thought has entered my mind regarding expirations, however, I think this is less of an issue as either (1) we can make expirations very long lived or (2) view expirations as information about the age of the chip.

I might be approaching this from the wrong angle, but would appreciate your take.

**Comment by lbeder** [comment]
Hey @ccamrobertson,
That's a neat idea. Our current thinking is that if you want attention to be considered irrevocable, you can make a schema with a flag that should tell people to ignore any revocations, but we may consider putting irrevocability into the protocol itself. Thank you for raising this.
